 
  export const expressions = {
      blink: {
        eyeBlinkLeft: 1,
        eyeBlinkRight: 1
      },
      happyTalk:{
        mouthSmileLeft: 0.3,
        mouthSmileRight: 0.3,
        mouthPressLeft: 0.1,
        mouthPressRight: 0.1,
        cheekSquintLeft: 0.5,
        cheekSquintRight: 0.5,
        cheekPuff: 0.25, 
        browInnerUp: 0.3,
        eyeSquintLeft: 0.2,
        eyeSquintRight: 0.2,
    },
    surprisedTalk: {
        mouthSmileLeft: 0.3,
        mouthSmileRight: 0.3,
        eyeWideLeft: 0.5,
        eyeWideRight: 0.5,
        browOuterUpLeft: 0.5,
        browOuterUpRight: 0.5,
        browInnerUp: 1
      },
    sadTalk:{
        browDownLeft: 0.7,
        browDownRight: 0.7,
        browInnerUp: 1,
        mouthFrownLeft: 0.2,
        mouthFrownRight: 0.2
    },
      smile: {
        eyeLookUpLeft: 0.2,
        eyeLookUpRight: 0.2,
        eyeSquintLeft: 0.2,
        eyeSquintRight: 0.2,
        jawOpen: 0.28,
        mouthClose: 0.1,
        mouthSmileLeft: 1,
        mouthSmileRight: 1,
        mouthShrugLower: 0.08,
        mouthPressLeft: 0.11,
        mouthPressRight: 0.11,
        browInnerUp: 0.2,
        cheekPuff: 0.5,
      },
      happySurprise: {
        mouthSmileLeft: 0.9,
        mouthSmileRight: 0.9,
        jawOpen: 0.4,  
        eyeWideLeft: 1,
        eyeWideRight: 1,
        browOuterUpLeft: 0.6,
        browOuterUpRight: 0.6,
      },
      happySurpriseReverse: {
        eyeWideLeft: 1,
        eyeWideRight: 1,
        browOuterUpLeft: 0.6,
        browOuterUpRight: 0.6,
      },
      pleased: {
        eyeLookUpLeft: 0.1,
        eyeLookUpRight: 0.1,
        eyeSquintLeft: 0.15,
        eyeSquintRight: 0.15,
        jawOpen: 0.15,
        mouthClose: 0.05,
        mouthSmileLeft: 0.8,
        mouthSmileRight: 0.8,
        mouthShrugLower: 0.4,
        mouthPressLeft: 0.07,
        mouthPressRight: 0.07,
        browInnerUp: 0.15,
        cheekPuff: 0.3,
      },
      attentive: {
        eyeLookUpLeft: 0.15,
        eyeLookUpRight: 0.15,
        eyeWideLeft: 0.3,
        eyeWideRight: 0.3,
        eyeSquintLeft: 0.4,
        eyeSquintRight: 0.4,
        mouthDimpleLeft: 0.4,
        mouthDimpleRight: 0.4,
        mouthSmileLeft: 0.8,
        mouthSmileRight: 0.8,
        mouthStretchLeft: 0.2,
        mouthStretchRight: 0.2,
        browInnerUp: 0.7,
        browOuterUpLeft: 0.15,
        browOuterUpRight: 0.15,
        cheekPuff: 0.3,
      },
      thoughtful: {
        eyeLookUpRight: 0.4,
        eyeLookUpLeft: 0.4,
        eyeSquintLeft: 0.8,
        eyeSquintRight: 0.8,
        mouthPucker: 0.35,
        mouthSmileLeft: 0.55,
        mouthSmileRight: 0.55,
        browDownLeft: 1,
        browDownRight: 1,
        browOuterUpLeft: 1,
        browOuterUpRight: 1,
        cheekSquintLeft: 0.4,
        cheekSquintRight: 0.4,
        mouthDimpleRight: 0.3,
        mouthDimpleLeft: 0.3,
        browInnerUp: 0.4
      },
      curious: {
        eyeLookUpLeft: 1,
        eyeLookUpRight: 1,
        mouthPressLeft: 0.5,
        mouthPressRight: 0.5,
        browInnerUp: 0.6,
        browOuterUpLeft: 0.4,
        browOuterUpRight: 1,
      },
      sad: {
        eyeSquintLeft: 0.6,
        eyeSquintRight: 0.6,
        eyeLookDownLeft: 0.3,
        eyeLookDownRight: 0.3,
        mouthFrownLeft: 1,
        mouthFrownRight: 1,
        mouthDimpleLeft: 0.2,
        mouthDimpleRight: 0.2,
        mouthStretchLeft: 0.4,
        mouthStretchRight: 0.4,
        mouthShrugUpper: 0.6,
        mouthLowerDownLeft: 0.2,
        mouthLowerDownRight: 0.2,
        browDownLeft: 0.4,
        browDownRight: 0.4,
        browInnerUp: 0.5,
        cheekPuff: 0.15,
        cheekSquintLeft: 0.6,
        cheekSquintRight: 0.6,
      },
      smirkLeft: {
        eyeLookUpRight: 0.2,
        eyeLookUpLeft: 0.2,
        eyeSquintRight: 0.2,
        eyeSquintLeft: 0.2,
        mouthClose: 0.1,
        mouthPucker: 0.5,
        mouthLeft: 0.65,
        mouthSmileLeft: 0.45,
        mouthSmileRight: 0.08,
        mouthStretchRight: 0.05,
        mouthUpperUpLeft: 0.15,
        browDownLeft: 0.3,
        browInnerUp: 0.4,
        cheekSquintLeft: 0.5,
        noseSneerLeft: 0.2,
        jawLeft: 0.15,
      },
      smirkRight: {
        eyeLookUpRight: 0.2,
        eyeLookUpLeft: 0.2,
        eyeSquintRight: 0.2,
        eyeSquintLeft: 0.2,
        mouthClose: 0.1,
        mouthPucker: 0.5,
        mouthRight: 0.65,
        mouthSmileRight: 0.45,
        mouthSmileLeft: 0.08,
        mouthStretchLeft: 0.05,
        mouthUpperUpRight: 0.15,
        browDownRight: 0.3,
        browInnerUp: 0.4,
        cheekSquintRight: 0.5,
        noseSneerRight: 0.2,
        jawRight: 0.15,
      },
      delighted: {
        mouthFunnel: 1,
        mouthSmileLeft: 1,
        mouthSmileRight: 1,
        mouthDimpleLeft: 0.7,
        mouthDimpleRight: 0.7,
        mouthStretchLeft: 1,
        mouthStretchRight: 1,
        browInnerUp: 1,
        browOuterUpLeft: 0.3,
        browOuterUpRight: 0.3,
        cheekSquintLeft: 0.3,
        cheekSquintRight: 0.3,
        eyeSquintRight: 0.2,
        eyeSquintLeft: 0.2,
        noseSneerRight: 0.1,
        noseSneerLeft: 0.1,
        jawOpen: 0.2,
      },
      neutral: {
        eyeSquintRight: 0.25,
        eyeSquintLeft: 0.25,
        eyeLookUpRight: 0.2,
        eyeLookUpLeft: 0.2,
        jawOpen: 0.15,
        mouthRollLower: 0.15,
        mouthSmileLeft: 0.25,
        mouthSmileRight: 0.25,
        mouthDimpleLeft: 0.05,
        mouthDimpleRight: 0.05,
        mouthPressLeft: 0.35,
        mouthPressRight: 0.35,
        browInnerUp: 0.4,
      },
      lookUpRight: {
        eyeLookUpLeft: 0.9,
        eyeLookUpRight: 0.9,
        eyeLookInLeft: 0.9,
        eyeLookOutRight: 0.9,
        browInnerUp: 0.8,
        browOuterUpLeft: 0.8,
        browOuterUpRight: 0.8,
      },
      lookUpLeft: {
        eyeLookUpLeft: 0.9,
        eyeLookUpRight: 0.9,
        eyeLookOutLeft: 0.9,
        eyeLookInRight: 0.9,
        browInnerUp: 0.8,
        browOuterUpLeft: 0.8,
        browOuterUpRight: 0.8,
      },
      lookDownRight: {
        eyeLookDownLeft: 0.9,
        eyeLookDownRight: 0.9,
        eyeLookInLeft: 0.9,
        eyeLookOutRight: 0.9,
        eyeBlinkRight: 0.1,
        eyeBlinkLeft: 0.1,
      },
      lookDownLeft: {
        eyeLookDownLeft: 0.9,
        eyeLookDownRight: 0.9,
        eyeLookOutLeft: 0.9,
        eyeLookInRight: 0.9,
        eyeBlinkRight: 0.1,
        eyeBlinkLeft: 0.1,
      }, 
      playful: {
        eyeSquintLeft: 0.25,
        eyeSquintRight: 0.25,
        jawForward: 0.3,
        jawOpen: 0.4,
        mouthLeft: 0.25,
        mouthRight: 0.25,
        mouthSmileLeft: 0.5,
        mouthSmileRight: 0.5,
        mouthShrugLower: 0.1,
        mouthPressLeft: 0.1,
        mouthPressRight: 0.1,
        browInnerUp: 0.1,
        cheekPuff: 0.15,
        tongueOut: 0.8
      }
    }
    
export const headMovements = {
        downRight: {
            eyeLookOutLeft: 0.12,
            eyeLookUpLeft: 0.12,
            eyeLookUpRight: 0.12,
            eyeLookInRight: 0.12,
            TrunLeft: 0.05,
            HeadDown: 0.12
        },
        downLeft: {
            eyeLookOutRight: 0.12,
            eyeLookUpLeft: 0.12,
            eyeLookUpRight: 0.12,
            eyeLookInLeft: 0.12,
            TrunRight: 0.05,
            HeadDown: 0.12
        },
        up: {
            HeadUp: 0.15,
            browInnerUp: 0.8,
            browOuterUpLeft: 0.6,
            browOuterUpRight: 0.6,
            eyeLookDownLeft: 0.25,
            eyeWideLeft: 0.25,
            eyeLookDownRight: 0.25,
            eyeWideRight: 0.25,
        },
        down: {
            HeadDown: 0.15,
            browInnerUp: 0.2,
            browOuterUpLeft: 0.2,
            browOuterUpRight: 0.2,
            eyeLookUpLeft: 0.25,
            eyeLookUpRight: 0.25,
        },
        turnRight: {
            eyeLookOutLeft: 0.12,
            eyeLookInRight: 0.12,
            TrunLeft: 0.05,
        },
        turnLeft: {
            eyeLookOutRight: 0.12,
            eyeLookInLeft: 0.12,
            TrunLeft: 0.05,
        },
        lookDownLeft: {
            eyeLookDownLeft: 0.25,
            eyeLookDownRight: 0.25,
            eyeLookInRight: 0.2,
            eyeLookOutLeft: 0.2,
            TrunLeft: 0.05,
            HeadDown: 0.12
        },
        lookDownRight: {
            eyeLookDownRight: 0.25,
            eyeLookDownLeft: 0.25,
            eyeLookInLeft: 0.2,
            eyeLookOutRight: 0.2,
            TrunRight: 0.03,
            HeadDown: 0.12
        },
        lookUpLeft: {
            eyeLookUpLeft: 0.25,
            eyeLookUpRight: 0.25,
            eyeLookOutLeft: 0.25,
            eyeLookInRight: 0.25,
            browInnerUp: 0.5,
            browOuterUpLeft: 0.42,
            browOuterUpRight: 0.42,
            HeadUp: 0.15,
            TrunLeft: 0.03
        },
        lookUpRight: {
            eyeLookUpRight: 0.25,
            eyeLookUpLeft: 0.25,
            eyeLookOutRight: 0.25,
            eyeLookInLeft: 0.25,
            browInnerUp: 0.5,
            browOuterUpLeft: 0.42,
            browOuterUpRight: 0.42,
            HeadUp: 0.15,
            TrunRight: 0.03
        },
        lookRight: {
            eyeLookOutLeft: 0.25,
            eyeLookInRight: 0.25,
            TrunRight: 0.03,
        },
        lookLeft: {
            eyeLookOutRight: 0.25,
            eyeLookInLeft: 0.25,
            TrunLeft: 0.03,
        },
    }
    const model = "ava2"
  
    const blendShapeIndicesAva2 = {"aa_02": 0, "eyeBlinkLeft": 1, "eyeLookDownLeft": 2, "eyeLookInLeft": 3, "eyeLookOutLeft": 4, "eyeLookUpLeft": 5, "eyeSquintLeft": 6, "eyeWideLeft": 7, "eyeBlinkRight": 8, "eyeLookDownRight": 9, "eyeLookInRight": 10, "eyeLookOutRight": 11, "eyeLookUpRight": 12, "eyeSquintRight": 13, "eyeWideRight": 14, "jawForward": 15, "jawLeft": 16, "jawRight": 17, "jawOpen": 18, "mouthClose": 19, "mouthFunnel": 20, "mouthPucker": 21, "mouthRight": 22, "mouthLeft": 23, "mouthSmileLeft": 24, "mouthSmileRight": 25, "mouthFrownRight": 26, "mouthFrownLeft": 27, "mouthDimpleLeft": 28, "mouthDimpleRight": 29, "mouthStretchLeft": 30, "mouthStretchRight": 31, "mouthRollLower": 32, "mouthRollUpper": 33, "mouthShrugLower": 34, "mouthShrugUpper": 35, "mouthPressLeft": 36, "mouthPressRight": 37, "mouthLowerDownLeft": 38, "mouthLowerDownRight": 39, "mouthUpperUpLeft": 40, "mouthUpperUpRight": 41, "browDownLeft": 42, "browDownRight": 43, "browInnerUp": 44, "browOuterUpLeft": 45, "browOuterUpRight": 46, "cheekPuff": 47, "cheekSquintLeft": 48, "cheekSquintRight": 49, "noseSneerLeft": 50, "noseSneerRight": 51, "ae_ax_ah_01": 52, "ao_03": 53, "ey_eh_uh_04": 54, "er_05": 55, "y_iy_ih_ix_06": 56, "w_uw_07": 57, "ow_08": 58, "aw_09": 59, "oy_10": 60, "ay_11": 61, "h_12": 62, "r_13": 63, "l_14": 64, "s_z_15": 65, "sh_ch_jh_zh_16": 66, "th_dh_17": 67, "f_v_18": 68, "d_t_n_19": 69, "k_g_ng_20": 70, "p_b_m_21": 71, "TrunLeft": 72, "TrunRight": 73, "HeadUp": 74, "HeadDown": 75, "HeadForward": 76, "HeadBackward": 77}
    const blendShapeIndicesAva = {eyeBlinkLeft: 0, eyeLookDownLeft: 1, eyeLookInLeft: 2, eyeLookOutLeft: 3, eyeLookUpLeft: 4, eyeSquintLeft: 5, eyeWideLeft: 6, eyeBlinkRight: 7, eyeLookDownRight: 8, eyeLookInRight: 9, eyeLookOutRight: 10, eyeLookUpRight: 11, eyeSquintRight: 12, eyeWideRight: 13, jawForward: 14, jawLeft: 15, jawRight: 16, jawOpen: 17, mouthClose: 18, mouthFunnel: 19, mouthPucker: 20, mouthRight: 21, mouthLeft: 22, mouthSmileLeft: 23, mouthSmileRight: 24, mouthFrownRight: 25, mouthFrownLeft: 26, mouthDimpleLeft: 27, mouthDimpleRight: 28, mouthStretchLeft: 29, mouthStretchRight: 30, mouthRollLower: 31, mouthRollUpper: 32, mouthShrugLower: 33, mouthShrugUpper: 34, mouthPressLeft: 35, mouthPressRight: 36, mouthLowerDownLeft: 37, mouthLowerDownRight: 38, mouthUpperUpLeft: 39, mouthUpperUpRight: 40, browDownLeft: 41, browDownRight: 42, browInnerUp: 43, browOuterUpLeft: 44, browOuterUpRight: 45, cheekPuff: 46, cheekSquintLeft: 47, cheekSquintRight: 48, noseSneerLeft: 49, noseSneerRight: 50, tongueOut: 51, ae_ax_ah_01: 52, aa_02: 53, ao_03: 54, ey_eh_uh_04: 55, er_05: 56, y_iy_ih_ix_06: 57, w_uw_07: 58, ow_08: 59, aw_09: 60, oy_10: 61, ay_11: 62, h_12: 63, r_13: 64, l_14: 65, s_z_15: 66, sh_ch_jh_zh_16: 67, th_dh_17: 68, f_v_18: 69, d_t_n_19: 70, k_g_ng_20: 71, p_b_m_21: 72}
    export const blendShape = model === "ava" ? blendShapeIndicesAva : blendShapeIndicesAva2
    
    export const randomExpressions = ['smile', 'attentive'];
  
  
  